model_path: '../../models/output/model_5_classes.pth'
image_dir: '../../data/processed/images/'
mask_dir: '../../data/processed/masks_5_classes/'
dataloader_dir: '../../models/output/dataloader_5_classes.pkl'
logs_dir: '../../models/output/logs'
batch_size: 64
num_classes: 6
num_epochs: 100
num_workers: 8
val_proportion: 0.1
test_proportion: 0.1